//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCMS.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookCatalog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookCatalog()
        {
            this.Authors = new HashSet<Author>();
            this.BookPlaces = new HashSet<BookPlace>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Summary { get; set; }
        public Nullable<decimal> ISBN { get; set; }
        public Nullable<int> PublicationYear { get; set; }
        public string Edition { get; set; }
        public string CoverImage { get; set; }
        public string ImageContentType { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Author> Authors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookPlace> BookPlaces { get; set; }
    }
}
