//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCMS.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionHistory
    {
        public int Id { get; set; }
        public Nullable<int> BookId { get; set; }
        public string TransactionType { get; set; }
        public Nullable<int> ApplicationUserId { get; set; }
        public Nullable<System.DateTime> TrasactionDate { get; set; }
    
        public virtual ApplicationUser ApplicationUser { get; set; }
        public virtual BookPlace BookPlace { get; set; }
    }
}
